steps:
  # 1. Собираем Docker-образ (теперь с новым адресом)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west3-docker.pkg.dev/$PROJECT_ID/webfactory-repo/webfactory:latest', '.']

  # 2. Пушим его в Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west3-docker.pkg.dev/$PROJECT_ID/webfactory-repo/webfactory:latest']

  # 3. Деплоим в Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'webfactory'
      - '--image'
      - 'europe-west3-docker.pkg.dev/$PROJECT_ID/webfactory-repo/webfactory:latest'
      - '--region'
      - 'europe-west3'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: CLOUD_LOGGING_ONLY